name: Build and upload image

on:
  push:
    tags:
      - "*"
  workflow_run:
    workflows: ["Pull Request(Python Dependabot)"]
    types: ["completed"]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      PLATFORMS: linux/amd64,linux/arm64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: get latest tag
        run: echo LATEST_TAG=`git tag -l --sort -authordate | head -n1` >> $GITHUB_ENV
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }}
