name: Pull Request(Dependabot)

on:
  pull_request:
    branches:
      - master
    paths:
      - requirements.txt

permissions:
  pull-requests: write

jobs:
  dependabot-auto-approve:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.6.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Approve a PR
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-tag:
    runs-on: ubuntu-latest
    needs:
      - dependabot-auto-approve
    steps:
      - uses: actions/checkout@v4
      - name: get latest tag
        run: echo LATEST_TAG=`git describe --tags --abbrev=0` >> $GITHUB_ENV
      - name: set new tag
        run: echo NEW_TAG=`echo ${{ env.LATEST_TAG }} | ( IFS=".$IFS" ; read a b c && echo $a.$b.$((c + 1)) )` >> $GITHUB_ENV
      - uses: richardsimko/update-tag@v1.0.7
        with:
          tag_name: ${{ env.NEW_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
